### ISSUE TITLE
Punti 06-04-2024

### ISSUE THREAD

**Issue by Sbrebbaz** [Sbrebbaz/ProgettoCodex#2]
- Capire se necessario definire il tabellone per le gestione di tutti i punti dei giocatori
- Disegnare / Abbozzare UI per AppState e GameState

**Comment by Dantillio** [comment]
definire le carte base

**Comment by Dantillio** [comment]
! i metodi Draw devono essere correlati con table per funzionare, perciò penso che dovremmo lasciare gestire la selezione del deck da cui pescare alla classe Game e player aggiunge ad hand quello che gli arriva !
